# Generated by Django 4.0.5 on 2022-09-24 02:43

import VMEServices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=VMEServices.models.Article.image_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=VMEServices.models.ArticleSeries.image_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('stripe_product_id', models.CharField(default=0, max_length=100)),
                ('slug', models.SlugField(max_length=128)),
                ('product_price', models.FloatField(default=0.0)),
                ('stok', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', max_length=128)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='services')),
                ('image', models.ImageField(upload_to='services')),
            ],
        ),
        migrations.CreateModel(
            name='serviceADM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=20)),
            ],
        ),
    ]
